backend/src/main/java/com/back/domain/bookmarks/constant/ReadState.java
backend/src/main/java/com/back/domain/bookmarks/entity/Bookmark.java

Bookmark 엔티티, ReadState enum 생ㅇ성
외래키 참조는 주석처리했습니다.

feat: Bookmark Entity, ReadState Enum 생성

---

backend/src/main/java/com/back/domain/reivew/review/entity/Review.java
backend/src/main/java/com/back/domain/review/review/entity/Review.java
backend/src/main/java/com/back/domain/review/review/repository/ReviewRepository.java
backend/src/main/java/com/back/domain/review/review/service/ReviewService.java

entity, service, repository 생성했습니다.

BE/리뷰 Entity 생성

---

backend/src/main/java/com/back/domain/user/user/Repository/UserRepository.java
backend/src/main/java/com/back/domain/user/user/controller/UserController.java
backend/src/main/java/com/back/domain/user/user/dto/UserDto.java
backend/src/main/java/com/back/domain/user/user/entity/User.java
backend/src/main/java/com/back/domain/user/user/service/UserService.java
backend/src/main/java/com/back/global/security/PasswardConfig.java
backend/src/test/java/com/back/domain/user/user/controller/UserControllerTest.java

**User**: 사용자 엔티티 구현
**UserService**: 회원가입, 이메일로 찾는 함수 구현
**UserController**: 회원가입 api구현, 이메일 중복시 예외처리
**PasswardConfig**: Bcrypt 방식으로 비밀번호 암호화
**UserControllerTest**: 회원가입 성공 테스트케이스 작성

[#1]feat: 회원가입 API 구현

---

backend/src/main/java/com/back/domain/bookmarks/controller/BookmarkController.java
backend/src/main/java/com/back/domain/bookmarks/dto/BookmarkCreateRequestDto.java
backend/src/main/java/com/back/domain/bookmarks/dto/BookmarkCreateResponseDto.java
backend/src/main/java/com/back/domain/bookmarks/entity/Bookmark.java
backend/src/main/java/com/back/domain/bookmarks/repository/BookmarkRepository.java
backend/src/main/java/com/back/domain/bookmarks/service/BookmarkService.java
backend/src/test/java/com/back/domain/bookmark/controller/BookmarkControllerTest.java

내 책 생성 API, TDD 구현
외래키 참조할 때 오류로, 추후 TDD 테스트 다시 진행 예정.

feat : 내 책 생성 API, TDD 구현

---

backend/build.gradle.kts
backend/src/main/java/com/back/domain/user/user/service/AuthTokenService.java
backend/src/main/java/com/back/global/security/SecurityConfig.java
backend/src/main/java/com/back/global/standard/util/Ut.java
backend/src/main/resources/application.yml

**jwt 의존성 추가**
**Ut**: JWT 생성, 검증, 디코딩
**SecurityConfig**: cors 설정, 기본 보안설정(현재는 모두 해제)
**AuthTokenService**: JWT 생성, 검증, 디코딩 하는 서비스 클래스

Feat: SpringSecurity + JWT 기반설정

---

backend/src/main/java/com/back/domain/book/author/repository/AuthorRepository.java
backend/src/main/java/com/back/domain/book/book/dto/BookSearchDto.java
backend/src/main/java/com/back/domain/book/book/entity/Book.java
backend/src/main/java/com/back/domain/book/book/repository/BookRepository.java
backend/src/main/java/com/back/domain/book/book/service/BookService.java
backend/src/main/java/com/back/domain/book/category/repository/CategoryRepository.java
backend/src/main/java/com/back/domain/book/wrote/repository/WroteRepository.java
backend/src/main/java/com/back/global/restTemplateConfig/RestTemplateConfig.java
backend/src/main/resources/application.yml
backend/src/test/java/com/back/domain/book/book/api/AladinApiManualTest.java
backend/src/test/java/com/back/domain/book/book/service/BookServiceIntegrationTest.java
backend/src/test/java/com/back/domain/book/book/service/BookServiceTest.java

Feat/be/book/25 open api연결

---

backend/src/main/java/com/back/domain/book/book/service/BookService.java
backend/src/test/java/com/back/domain/book/book/service/BookServiceTest.java

설계당시에 계획했던 8개로 나눠서 카테고리를 관리하는 방식으로 코드를 짜봤는데, 유지보수도 힘들어 보이고 가독성도 떨어져서 그냥 2단계에 적혀있는 카테고리를 사용하는 방식을 채택했습니다.

fix:카테고리를 2번째 깊이에 있는 것을 추출하여 사용함

---

backend/src/main/java/com/back/domain/member/member/controller/MemberController.java

**MemberController**: 내 정보 조회 API 추가

Feat: 내 정보 조회 API 구현

---

backend/src/main/java/com/back/domain/member/member/controller/MemberController.java
backend/src/main/java/com/back/domain/member/member/entity/Member.java
backend/src/main/java/com/back/domain/member/member/service/AuthTokenService.java
backend/src/main/java/com/back/domain/member/member/service/MemberService.java
backend/src/main/java/com/back/global/rq/Rq.java
backend/src/main/resources/application.yml

**AuthTokenService**: refresh토큰 생성로직 구현
**MemberService/Member**: refresh토큰 생성/업데이트/삭제 로직 구현
**MemberController**: login/logout에 refresh토큰 관련 로직 도입

Feat: refresh토큰 구현

---

frontend/src/app/books/[bookId]/page.tsx
frontend/src/app/books/page.tsx
frontend/src/app/layout.tsx
frontend/src/app/my-books/[bookId]/notes/page.tsx
frontend/src/app/my-books/[bookId]/page.tsx
frontend/src/app/my-books/[bookId]/review/page.tsx
frontend/src/app/my-books/page.tsx

버튼을 통해 페이지 이동
useRouter를 사용해서 버튼을 통해 페이지 이동 기능을 만들었습니다.
아직 login 감지 기능이 없어서 /my-books는 직접 이동해야합니다.

FE/ 버튼 클릭으로 이동 구현 #62

---

backend/src/main/java/com/back/domain/member/member/controller/MemberController.java
backend/src/main/java/com/back/global/security/JwtAuthenticationFilter.java
backend/src/main/java/com/back/global/security/SecurityConfig.java
frontend/src/app/_hooks/auth-context.tsx
frontend/src/app/_hooks/useLogin.ts
frontend/src/app/_hooks/useSignup.ts
frontend/src/app/layout.tsx
frontend/src/app/login/page.tsx
frontend/src/lib/apiFetch.ts
frontend/src/lib/toast.ts
frontend/src/types/auth.ts

**useLogin/useSignup**: 로그인/회원가입 위한 훅 구현
**layout**: AuthProvider로 감싸 전역 상태 관리
**login/page**: 로그인 페이지 구현

Feat: 회원가입,로그인 페이지 구현

---

backend/src/main/java/com/back/domain/book/book/service/BookService.java
backend/src/main/java/com/back/domain/book/client/aladin/AladinApiClient.java
backend/src/main/java/com/back/domain/book/client/aladin/dto/AladinBookDto.java
backend/src/test/java/com/back/domain/book/book/service/BookServiceTest.java

Api가져오는 로직을 기존 Service클래스에서 AladinApiClient클래스로 옮기고, 관련해서 리팩토링 했습니다.

refactor:AladinApiClient로 분리

---

backend/src/main/java/com/back/domain/member/member/controller/MemberController.java
backend/src/main/java/com/back/domain/member/member/service/MemberService.java
backend/src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java

**MemberController**: 회원 탈퇴 API 구현
**MemberControllerTest**: 탈퇴 성공 테스트 추가

Feat: 회원 탈퇴 API 구현

---

backend/src/main/java/com/back/domain/review/review/controller/ReviewController.java
backend/src/main/java/com/back/domain/review/review/dto/ReviewWithIdDto.java
backend/src/main/java/com/back/domain/review/review/service/ReviewService.java
backend/src/main/java/com/back/domain/review/reviewRecommend/entity/ReviewRecommend.java
backend/src/main/java/com/back/domain/review/reviewRecommend/service/ReviewRecommendService.java
backend/src/main/java/com/back/global/initData/BaseInitData.java
backend/src/test/java/com/back/domain/review/reviewRecommend/controller/ReviewRecommendController.java

리뷰 추천 수정
리뷰 추천 수정 기능을 작성했고
리뷰는 전과 같은 값을 저장하려고 하면 400 상태코드를 반환하고
이전과 다른 값을 저장하려고 할 때만 저장하고
해당 리뷰의 좋아요, 싫어요가 둘 다 변경되기에 둘 다 업데이트를 시키는 작업을 했습니다.
테스트 케이스를 작성 했습니다.
close #79

Feat/be/review recommend/#79 modify

---

backend/src/main/java/com/back/domain/book/book/controller/BookController.java
backend/src/main/java/com/back/domain/book/book/dto/BookDetailDto.java
backend/src/main/java/com/back/domain/book/book/dto/BookSearchDto.java
backend/src/main/java/com/back/domain/book/book/entity/Book.java
backend/src/main/java/com/back/domain/book/book/service/BookService.java
backend/src/main/java/com/back/domain/bookmarks/repository/BookmarkRepository.java
backend/src/main/java/com/back/domain/bookmarks/service/BookmarkService.java
backend/src/main/java/com/back/domain/review/review/dto/ReviewResponseDto.java
backend/src/main/java/com/back/domain/review/review/repository/ReviewRepository.java
backend/src/test/java/com/back/domain/book/book/controller/BookControllerTest.java

Feat/be/book/81 book단건조회

---

backend/src/main/java/com/back/domain/book/book/controller/BookController.java
backend/src/main/java/com/back/global/initData/BaseInitData.java
frontend/next.config.ts
frontend/package-lock.json
frontend/src/app/books/page.tsx
frontend/src/types/book.ts

feat:책 전체조회 구현

---

backend/src/main/java/com/back/domain/review/review/controller/ReviewController.java
backend/src/main/java/com/back/domain/review/reviewRecommend/service/ReviewRecommendService.java
backend/src/main/java/com/back/global/initData/BaseInitData.java
backend/src/test/java/com/back/domain/review/reviewRecommend/controller/ReviewRecommendController.java

리뷰 추천 삭제 기능
리뷰 추천 삭제 기능을 구현했고 테스트 케이스도 작성했습니다.
init data의 책 데이터 초기화 코드를 주석처리했습니다.
close #98

 BE/리뷰추천 삭제 구현

---

backend/src/main/java/com/back/domain/member/member/controller/MemberController.java
backend/src/main/java/com/back/domain/member/member/dto/MemberJoinReqDto.java
backend/src/main/java/com/back/domain/member/member/dto/MemberLoginReqDto.java
backend/src/main/java/com/back/domain/member/member/dto/MemberLoginResDto.java
backend/src/main/java/com/back/global/rq/Rq.java
backend/src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java

Refactor:  Dto 분리 및 코드 리팩토링

---

backend/src/main/java/com/back/domain/note/controller/NoteController.java
backend/src/main/java/com/back/domain/note/dto/NoteDto.java
backend/src/main/java/com/back/domain/note/entity/Note.java
backend/src/main/java/com/back/global/initData/BaseInitData.java
backend/src/test/java/com/back/domain/note/controller/NoteControllerTest.java
frontend/package-lock.json
frontend/src/app/bookmark/[id]/notes/_hook/useNote.tsx
frontend/src/app/bookmark/[id]/notes/page.tsx

- FE: 노트페이지에 필요한 데이터 받아와서 뿌려주기
- FE: 노트수정, 노트삭제, 노트작성
- FE: 노트 수정, 작성할시 모달컴포넌트에서 글자가 컴포넌트 범위 밖으로 넘어가는 것 수정
- FE: 노트리스트 컴포넌트에서 내용이 컴포넌트 범위 밖으로 넘어가는 것 수정
- FE: 노트 사이즈 수정
- BE: 테이블 nullable, size 변경
- BE: 노트 Length 변경
Close #71

Feat: 노트 페이지 구현

---

backend/src/main/java/com/back/domain/book/category/controller/CategoryController.java
backend/src/main/java/com/back/domain/book/category/dto/CategoryDto.java
backend/src/main/java/com/back/domain/book/category/service/CategoryService.java
backend/src/main/java/com/back/domain/bookmarks/entity/Bookmark.java
backend/src/main/java/com/back/domain/bookmarks/service/BookmarkService.java
backend/src/main/java/com/back/global/security/JwtAuthenticationFilter.java
backend/src/main/java/com/back/global/security/SecurityConfig.java
backend/src/test/java/com/back/domain/book/category/controller/CategoryControllerTest.java
frontend/src/app/bookmark/[id]/_components/bookInfoTab.tsx
frontend/src/app/bookmark/[id]/_components/bookmarkSummaryCard.tsx
frontend/src/app/bookmark/[id]/_components/notesTab.tsx
frontend/src/app/bookmark/[id]/_components/reviewTab.tsx
frontend/src/app/bookmark/[id]/page.tsx
frontend/src/app/bookmark/_components/bookmarkCard.tsx
frontend/src/app/bookmark/_components/bookmarkFilters.tsx
frontend/src/app/bookmark/_components/bookmarkStats.tsx
frontend/src/app/bookmark/_components/paginationControls.tsx
frontend/src/app/bookmark/page.tsx
frontend/src/lib/apiFetch.ts
frontend/src/lib/bookmarkUtils.tsx
frontend/src/types/bookmarkAPI.js
frontend/src/types/category.ts

feat:
BE 카테고리 조회 TDD, API 구현(인증 제외)
fix:
BE 북마크 삭제 시 리뷰 삭제 추가
BE readState 상태에 따른 값 초기화
refactor:
FE 북마크 목록, 상세페이지, apiFetch.ts로 호출로직 수정

BE/ 카테고리 조회 추가

---

backend/src/main/java/com/back/global/initData/BaseInitData.java
frontend/src/app/bookmark/[id]/notes/_hook/useNote.tsx
frontend/src/app/bookmark/[id]/notes/_hook/useSafeFetch.tsx
frontend/src/app/bookmark/[id]/notes/page.tsx

- FE/ 비회원 url 접근시 로그인 페이지 이동
- FE/ 회원이 인가되지 않은 url 접근시 홈화면 이동
Close #128

feat: 비회원 or 인가되지않는 회원 url 접근시 조치

---

frontend/.idea/.gitignore
frontend/.idea/frontend.iml
frontend/.idea/inspectionProfiles/Project_Default.xml
frontend/.idea/misc.xml
frontend/.idea/modules.xml
frontend/.idea/vcs.xml
frontend/package-lock.json
frontend/src/app/_hooks/useFormValidation.ts
frontend/src/app/_hooks/useLogin.ts
frontend/src/app/_hooks/useSignup.ts
frontend/src/app/login/page.tsx
frontend/src/app/profile/page.tsx
frontend/src/app/utils/formValidation.ts
frontend/src/components/ui/form-field.tsx
frontend/src/components/ui/password-input.tsx

**utils/formValidation.ts**: 재사용 가능한 검증 함수들
**_hooks/useFormValidation.ts**: 폼 상태 관리 커스텀 훅
**PasswordInput**: 비밀번호 표시/숨김 토글 기능
**FormField**: 라벨, 에러 메시지 통합 관리

Refactor: 로그인/프로필 페이지 컴포넌트 구조 개선

---

frontend/package-lock.json
frontend/src/app/bookmark/page.tsx
frontend/src/app/page.tsx

FE 메인화면의 로그인 시 표시되는 데이터를 API 응답 데이터로 변경
FE 북마크 목록의 세미콜론 제거
FE  패키지 오류 수정

Feat FE 로그인 시 메인화면 데이터 변경

---

backend/src/main/generated/com/back/domain/book/author/entity/QAuthor.java
backend/src/main/generated/com/back/domain/book/book/entity/QBook.java
backend/src/main/generated/com/back/domain/book/category/entity/QCategory.java
backend/src/main/generated/com/back/domain/book/wrote/entity/QWrote.java
backend/src/main/generated/com/back/domain/bookmarks/entity/QBookmark.java
backend/src/main/generated/com/back/domain/member/member/entity/QMember.java
backend/src/main/generated/com/back/domain/note/entity/QNote.java
backend/src/main/generated/com/back/domain/review/review/entity/QReview.java
backend/src/main/generated/com/back/domain/review/reviewRecommend/entity/QReviewRecommend.java
backend/src/main/generated/com/back/global/jpa/entity/QBaseEntity.java
backend/src/main/java/com/back/domain/book/book/service/BookService.java

외부 API에서 받아온 값을 DB에 넣고 값을 출력했는데, 검색 로직의 차이로 인해 오류가 발생함.
받아온 책들을 DB로 넘기고, DB에서 다시 검색하여 출력하는 방식으로 변경하였다.

fix:페이징 문제 해결

---

backend/src/main/java/com/back/domain/member/member/entity/Member.java

**member**: member엔티티에 양방향 관계 추가

[#157]fix:외래키 제약조건 위반문제 해결

---

backend/src/main/generated/com/back/domain/member/member/entity/QMember.java
backend/src/main/java/com/back/domain/book/book/repository/BookRepositoryCustom.java
backend/src/main/java/com/back/domain/book/book/repository/BookRepositoryImpl.java
backend/src/main/java/com/back/domain/book/book/service/BookService.java
frontend/src/app/books/page.tsx
frontend/src/types/book.ts

정렬이 전체 데이터에서 이루어지는 것이 아니라 페이지 내부에서 일어나고 있었음
기존에 데이터를 받아와서 정렬해서 뿌리는 방식에서 DB에서 정렬된 데이터를 꺼내오는 방식으로 수정함.

fix:정렬 페이징 외부에서 적용

---

frontend/src/app/books/page.tsx

책 탐색 페이지에서 로그아웃 누르면 리렌더링이 안되는 문제가 있어서 해결했습니다.

fix:책탐색 로그아웃 버그

---

backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

Setting: 운영환경셋팅(임시)

---

frontend/src/app/bookmark/[id]/review/page.tsx

버그 수정
리뷰를 작성할 때 작성 후 이동하지 않아 DB상으로 업데이트되지 않은 상태로 페이지 이동을 해 반영되지 않았던 점 수정

[#168]fix: 리뷰 저장 후 페이지 이동

---

backend/src/main/resources/application-prod.yml

Setting: yml파일 재설정
